version: "2"

services:
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-default
    expose:
      - 4004
    depends_on:
      - validator
    entrypoint: settings-tp -C tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
        \""

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-default
    expose:
      - 4004
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8080

  client:
    image: hyperledger/sawtooth-all:1.0
    container_name: sawtooth-client-default
    expose:
      - 8080
      - 4004
    depends_on:
      - rest-api
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""
